name: Automerge

on:
  schedule:
    # You can setup schedule here
    - cron: '6 * * * *'

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://Nikhitamanjunath:${{secrets.GITHUB_TOKEN}}@github.com/Nikhitamanjunath/Nikhita.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: b3

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/Nikhitamanjunath/Nikhita.git

  # replace "master" with your master branch name
  MASTER_BRANCH: b2

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "nikhita928@gmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
